name: About Build

on:
  push:
    branches:
      - main
    paths:
      - '_abouts/site-description.md'

permissions:
  contents: write   # required for pushing changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0                     # <<< important for any later git ops

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination ./_site

      # Copy the rendered HTML from the built _site into the source _includes folder
      - name: Copy rendered site-description into _includes and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          SRC_PATH="./_site/abouts/site-description.html"
          DEST_PATH="_includes/site-description.html"
          if [ ! -f "$SRC_PATH" ]; then
            echo "Rendered file not found at $SRC_PATH"
            exit 1
          fi
          mkdir -p "$(dirname "$DEST_PATH")"
          cp -f "$SRC_PATH" "$DEST_PATH"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$DEST_PATH"
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: import rendered site-description [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          fi

      # If you want the deployment to include the just-committed include, rebuild & deploy:
      - name: Rebuild Jekyll site (so deployment includes new include)
        run: bundle exec jekyll build --destination ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
