name: Generate site content from Zotero CSV

on:
  push:
    branches:
      - main                     
    paths:
      - 'assets/data/books_zotero.csv' 

jobs:
  generate:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'  # ← match your local Python version if needed
      
      
      - name: Create venv
        run: |
          python -m venv assets/env
          assets/env/bin/python -m pip install --upgrade pip setuptools wheel
          assets/env/bin/pip install -r requirements.txt

      - name: Run generator
        run: assets/env/bin/python assets/env/src/morel-generate.py
        # ↑ update the path to your actual script and/or input file if different

      # Optional: commit and push generated content if the script changes files
      - name: Commit and push generated content
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generate content from updated CSV"
            git push origin HEAD:${{ github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
